def menu(): 
    print ("╔═══════════════════════════════════════════╗")
    print ("║         Aplikasi Makan Sehat🥙            ║")
    print ("╚═══════════════════════════════════════════╝")
    print ("║Pilih program yang ingin anda jalankan:    ║")
    print ("║1. Cek Manual Gizi Makanan                 ║") 
    print ("║2. Cek BMI anda                            ║") 
    print ("║3. Resep harian                            ║") 
    print ("║4. Cek Otomatis Gizi Makanan               ║") 
    print ("║99. Keluar                                 ║")
    print ("╚═══════════════════════════════════════════╝")